#!/bin/sh

# PackPack version
PACKVERSION=1.0.0

# Source directory
SOURCEDIR=${SOURCEDIR:-$PWD}

# Build directory
BUILDDIR=${BUILDDIR:-${SOURCEDIR}/build}

# Docker repository to use
DOCKER_REPO=${DOCKER_REPO:-packpack/packpack}

# Extra parameters for docker run.
PACKPACK_EXTRA_DOCKER_RUN_PARAMS="${PACKPACK_EXTRA_DOCKER_RUN_PARAMS:-}"

# CPACK generators
CPACK_GENERATORS="${CPACK_GENERATORS:-DEB}"

# Set CI variable to CI provider name
CI=""
if [ "${APPVEYOR:-}" = "True" -o "${APPVEYOR:-}" = "true" ]; then
    # https://www.appveyor.com/docs/environment-variables/
    CI="appveyor"
elif [ "${CIRCLECI:-}" = "true" ]; then
    # https://circleci.com/docs/2.0/env-vars/
    CI="circle"
elif [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
    CI="github"
elif [ "${GITLAB_CI:-}" = "true" ]; then
    # https://docs.gitlab.com/ee/ci/variables/
    CI="gitlab"
elif [ "${TRAVIS:-}" = "true" ]; then
    # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
    CI="travis"
fi

# Docker architecture
if [ -z "${ARCH}" ]; then
    # Use uname -m instead of HOSTTYPE
    case "$(uname -m)" in
        i*86) ARCH="i386" ;;
        arm*) ARCH="armhf" ;;
        x86_64) ARCH="x86_64"; ;;
        aarch64) ARCH="aarch64" ;;
        *) ARCH="${HOSTTYPE}" ;;
    esac
fi

# Docker image to use
if [ -z "${DOCKER_IMAGE}" ]; then
    if [ -n "${OS}" ] && [ -n "${DIST}" ]; then
        # Non-numeric dist, e.g. debian-sid, ubuntu-precise, etc.
        DOCKER_IMAGE="${OS}-${DIST}"
    else
        # Use ubuntu-xenial docker image if OS or DIST is invalid
        DOCKER_IMAGE=ubuntu-bionic
    fi

    if [ "${ARCH}" != "x86_64" ]; then
        DOCKER_IMAGE="${DOCKER_IMAGE}-${ARCH}"
    fi
fi

version() {
    echo "PackPack version ${PACKVERSION}"
}

usage() {
    echo "# PackPack version ${PACKVERSION}"
    echo ""
    echo "Usage: OS=ubuntu DIST=xenial $0 [CPack Generators] [CMake options]"
    echo ""
    echo "## Environment Variables"
    echo ""
    echo " * PRODUCT - the name of software product, e.g. 'tarantool'"
    echo " * ARCH - architecture, e.g i386, x86_64, armhf (${ARCH})"
    echo " * OS - the name of distribution, e.g. debian or fedora (${OS})"
    echo " * DIST - the version of distribution, e.g. xenial or 24 (${DIST})"
    echo " * BUILDDIR - directory used for out-of-source build (${BUILDDIR})"
    echo " * DOCKER_REPO - Docker repository to use (${DOCKER_REPO})"
    echo ""
    echo "The actual list of distribution is available on Docker Hub:"
    echo ""
    echo "   https://hub.docker.com/r/${DOCKER_REPO}/tags/"
    echo ""
    echo "## Documentation"
    echo ""
    echo " * See https://github.com/packpack/packpack"
    echo ""
}

case "$1" in
    -V|--version)
        version
        exit 0
    ;;
    -h|--help)
        usage
        exit 1
        ;;
    *) ;;
esac

#
# Create an entry point for Docker to allow builds from non-root user
#
mkdir -p ${BUILDDIR}

if [ "${OS}" = "alpine" ]; then
    (
        echo "#!/bin/sh";
        echo "set -x";
        echo "adduser -u $(id -u) -D $USER";
        echo "adduser $USER adm";
        echo "adduser $USER wheel";
        echo "adduser $USER abuild";
        echo "export HOME=/home/$USER" ;
        echo "abuild-keygen -a -i -n";
        echo "su-exec $USER \"\$@\"";
    ) > ${BUILDDIR}/userwrapper.sh
else
    (
        echo "#!/bin/sh";
        echo "set -x";
        echo "useradd -u $(id -u) $USER";
        echo "usermod -a -G sudo $USER 2>/dev/null || :";
        echo "usermod -a -G wheel $USER 2>/dev/null || :";
        echo "usermod -a -G adm $USER 2>/dev/null || :";
        echo "export HOME=/home/$USER" ;
        echo "exec chroot --userspec=$USER / \"\$@\"";
    ) > ${BUILDDIR}/userwrapper.sh
fi


chmod a+x ${BUILDDIR}/userwrapper.sh

#
# Docker command
#
(
    echo "#!/bin/sh";
    echo "set -x";
    echo "CPACK_GENERATORS=\"\$1\"";
    echo "shift 1";
    echo "CMAKE_OPTS=\"\$@\"";
    echo "cd /build";
    echo "sudo apt-get -y update && \\";
    echo "    sudo apt-get -y install pkg-config systemd uuid-dev libsodium-dev libzmq3-dev libczmq-dev";
    echo "if [ \"\$?\" -ne 0 ]; then"
    echo "    sudo yum install -y epel-release && \\";
    echo "       sudo yum-config-manager --add-repo http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-draft/CentOS_7/network:messaging:zeromq:release-draft.repo && \\";
    echo "       sudo yum install -y pkgconfig uuid-devel libsodium-devel zeromq-devel czmq-devel && \\";
    echo "       sudo sed -i -e '/Cflags:/ s/-I\${libdir}\/pgm-5.2\/include//' /usr/lib64/pkgconfig/openpgm-5.2.pc";
    echo "fi";
    echo "if [ \"\$?\" -ne 0 ]; then";
    echo "    exit 1";
    echo "fi";
    echo "cmake3 \${CMAKE_OPTS} /source";
    echo "if [ \"\$?\" -ne 0 ]; then";
    echo "    cmake \${CMAKE_OPTS} /source";
    echo "fi";
    echo "if [ \"\$?\" -ne 0 ]; then";
    echo "    exit 1";
    echo "fi";
    echo "cpack -V -G \"\${CPACK_GENERATORS}\"";
) > ${BUILDDIR}/usercmd.sh

chmod a+x ${BUILDDIR}/usercmd.sh

#
# Save defined configuration variables to ./env file
#
env | grep -E "^PRODUCT=|^VERSION=|^RELEASE=|^ABBREV=|^TARBALL_|^CHANGELOG_|^CCACHE_|^PACKAGECLOUD_|^SMPFLAGS=|^OS=|^DIST=|^VAR_|^LD_LIBRARY_PATH=" \
    > ${BUILDDIR}/env

#
# Setup cache directory
#
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/packpack"
mkdir -p "${CACHE_DIR}/ccache"

#
# Fix security context for selinux
#
chcon -Rt svirt_sandbox_file_t ${SOURCEDIR} ${BUILDDIR} \
    1> /dev/null 2> /dev/null || :

#
# Start Docker
#
set -ex
docker pull ${DOCKER_REPO}:${DOCKER_IMAGE}
docker run \
        ${PACKPACK_EXTRA_DOCKER_RUN_PARAMS} \
        --volume "${SOURCEDIR}:/source:ro" \
        --volume "${BUILDDIR}:/build" \
        --env-file ${BUILDDIR}/env \
        --workdir /build \
        --rm=true --tty=true \
        --entrypoint=/build/userwrapper.sh \
        -e XDG_CACHE_HOME=/cache \
        -e CCACHE_DIR=/cache/ccache \
        -e TMPDIR=/tmp \
        -e CI=${CI} \
        --volume "${CACHE_DIR}:/cache" \
        ${DOCKER_REPO}:${DOCKER_IMAGE} \
        /build/usercmd.sh "$@"
retcode=$?
rm -f ${BUILDDIR}/userwrapper.sh ${BUILDDIR}/usercmd.sh ${BUILDDIR}/env
exit $retcode
# vim: filetype=sh tabstop=4 shiftwidth=4 softtabstop=4 expandtab
