/*
  Register definitions for slave core: AFC MGMT registers

  * File           : wb_afc_mgmt_regs.h
  * Author         : auto-generated by wbgen2 from afc_mgmt_regs.wb
  * Created        : Fri Aug 25 16:13:48 2017
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE afc_mgmt_regs.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_AFC_MGMT_REGS_WB
#define __WBGEN2_REGDEFS_AFC_MGMT_REGS_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Clock distribution control register */

/* definitions for field: Si 571 Output Enable in reg: Clock distribution control register */
#define AFC_MGMT_CLK_DISTRIB_SI57X_OE         WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Reserved in reg: Clock distribution control register */
#define AFC_MGMT_CLK_DISTRIB_RESERVED_MASK    WBGEN2_GEN_MASK(1, 31)
#define AFC_MGMT_CLK_DISTRIB_RESERVED_SHIFT   1
#define AFC_MGMT_CLK_DISTRIB_RESERVED_W(value) WBGEN2_GEN_WRITE(value, 1, 31)
#define AFC_MGMT_CLK_DISTRIB_RESERVED_R(reg)  WBGEN2_GEN_READ(reg, 1, 31)

/* definitions for register: Dummy */

/* definitions for field: Reserved in reg: Dummy */
#define AFC_MGMT_DUMMY_RESERVED_MASK          WBGEN2_GEN_MASK(0, 32)
#define AFC_MGMT_DUMMY_RESERVED_SHIFT         0
#define AFC_MGMT_DUMMY_RESERVED_W(value)      WBGEN2_GEN_WRITE(value, 0, 32)
#define AFC_MGMT_DUMMY_RESERVED_R(reg)        WBGEN2_GEN_READ(reg, 0, 32)
/* [0x0]: REG Clock distribution control register */
#define AFC_MGMT_REG_CLK_DISTRIB 0x00000000
/* [0x4]: REG Dummy */
#define AFC_MGMT_REG_DUMMY 0x00000004
#endif
