/*
 * Copyright (C) 2014 LNLS (www.lnls.br)
 * Author: Joao Brito <joao.brito@lnls.br>
 *
 * Released according to the GNU GPL, version 3 or any later version.
 */

#ifndef _SM_IO_AFC_TIMING_EXPORTS_H_
#define _SM_IO_AFC_TIMING_EXPORTS_H_

#include "disptable.h"

extern disp_op_t afc_timing_set_get_link_status_exp;
extern disp_op_t afc_timing_set_get_rxen_status_exp;
extern disp_op_t afc_timing_set_get_ref_clk_locked_exp;
extern disp_op_t afc_timing_set_get_evren_exp;
extern disp_op_t afc_timing_set_get_alive_exp;
extern disp_op_t afc_timing_set_get_freq_sample_rate_prescale_exp;
extern disp_op_t afc_timing_set_get_amc_en_exp;
extern disp_op_t afc_timing_set_get_amc_pol_exp;
extern disp_op_t afc_timing_set_get_amc_log_exp;
extern disp_op_t afc_timing_set_get_amc_itl_exp;
extern disp_op_t afc_timing_set_get_amc_src_exp;
extern disp_op_t afc_timing_set_get_amc_dir_exp;
extern disp_op_t afc_timing_set_get_amc_pulses_exp;
extern disp_op_t afc_timing_set_get_amc_evt_exp;
extern disp_op_t afc_timing_set_get_amc_dly_exp;
extern disp_op_t afc_timing_set_get_amc_wdt_exp;
extern disp_op_t afc_timing_set_get_fmc1_en_exp;
extern disp_op_t afc_timing_set_get_fmc1_pol_exp;
extern disp_op_t afc_timing_set_get_fmc1_log_exp;
extern disp_op_t afc_timing_set_get_fmc1_itl_exp;
extern disp_op_t afc_timing_set_get_fmc1_src_exp;
extern disp_op_t afc_timing_set_get_fmc1_dir_exp;
extern disp_op_t afc_timing_set_get_fmc1_pulses_exp;
extern disp_op_t afc_timing_set_get_fmc1_evt_exp;
extern disp_op_t afc_timing_set_get_fmc1_dly_exp;
extern disp_op_t afc_timing_set_get_fmc1_wdt_exp;
extern disp_op_t afc_timing_set_get_fmc2_en_exp;
extern disp_op_t afc_timing_set_get_fmc2_pol_exp;
extern disp_op_t afc_timing_set_get_fmc2_log_exp;
extern disp_op_t afc_timing_set_get_fmc2_itl_exp;
extern disp_op_t afc_timing_set_get_fmc2_src_exp;
extern disp_op_t afc_timing_set_get_fmc2_dir_exp;
extern disp_op_t afc_timing_set_get_fmc2_pulses_exp;
extern disp_op_t afc_timing_set_get_fmc2_evt_exp;
extern disp_op_t afc_timing_set_get_fmc2_dly_exp;
extern disp_op_t afc_timing_set_get_fmc2_wdt_exp;
extern disp_op_t afc_timing_set_get_rtm_freq_kp_exp;
extern disp_op_t afc_timing_set_get_rtm_freq_ki_exp;
extern disp_op_t afc_timing_set_get_rtm_phase_kp_exp;
extern disp_op_t afc_timing_set_get_rtm_phase_ki_exp;
extern disp_op_t afc_timing_set_get_rtm_phase_set_exp;
extern disp_op_t afc_timing_set_get_rtm_phase_navg_exp;
extern disp_op_t afc_timing_set_get_rtm_phase_div_exp_exp;
extern disp_op_t afc_timing_set_get_rtm_rfreq_hi_exp;
extern disp_op_t afc_timing_set_get_rtm_rfreq_lo_exp;
extern disp_op_t afc_timing_set_get_rtm_n1_exp;
extern disp_op_t afc_timing_set_get_rtm_hs_div_exp;
extern disp_op_t afc_timing_set_get_afc_freq_kp_exp;
extern disp_op_t afc_timing_set_get_afc_freq_ki_exp;
extern disp_op_t afc_timing_set_get_afc_phase_kp_exp;
extern disp_op_t afc_timing_set_get_afc_phase_ki_exp;
extern disp_op_t afc_timing_set_get_afc_phase_set_exp;
extern disp_op_t afc_timing_set_get_afc_phase_navg_exp;
extern disp_op_t afc_timing_set_get_afc_phase_div_exp_exp;
extern disp_op_t afc_timing_set_get_afc_rfreq_hi_exp;
extern disp_op_t afc_timing_set_get_afc_rfreq_lo_exp;
extern disp_op_t afc_timing_set_get_afc_n1_exp;
extern disp_op_t afc_timing_set_get_afc_hs_div_exp;

extern const disp_op_t *afc_timing_exp_ops [];

#endif

