# Read header file and extract version numbers

file(READ
    "${PROJECT_SOURCE_DIR}/include/acq_client_classes.h"
    _ACQCLIENT_H_CONTENTS
)

string(REGEX REPLACE
    ".*#define ACQ_CLIENT_VERSION_MAJOR ([0-9]+).*"
    "\\1" ACQCLIENT_VERSION_MAJOR
    "${_ACQCLIENT_H_CONTENTS}"
)
string(REGEX REPLACE
    ".*#define ACQ_CLIENT_VERSION_MINOR ([0-9]+).*"
    "\\1" ACQCLIENT_VERSION_MINOR
    "${_ACQCLIENT_H_CONTENTS}"
)
string(REGEX REPLACE
    ".*#define ACQ_CLIENT_VERSION_PATCH ([0-9]+).*"
    "\\1" ACQCLIENT_VERSION_PATCH
    "${_ACQCLIENT_H_CONTENTS}"
)

set(ACQCLIENT_VERSION
    "${ACQCLIENT_VERSION_MAJOR}.${ACQCLIENT_VERSION_MINOR}.${ACQCLIENT_VERSION_PATCH}"
)

message(STATUS "Detected ACQCLIENT Version - ${ACQCLIENT_VERSION}")
