  /*
 * Copyright (C) 2014 LNLS (www.lnls.br)
 * Author: Joao Brito <joao.brito@lnls.br>
 *
 * Released according to the GNU GPL, version 3 or any later version.
 */

#ifndef _SM_IO_AFC_TIMING_CODES_H_
#define _SM_IO_AFC_TIMING_CODES_H_

#include <inttypes.h>

/* Messaging OPCODES */
#define AFC_TIMING_OPCODE_TYPE                    uint32_t
#define AFC_TIMING_OPCODE_SIZE                    (sizeof (AFC_TIMING_OPCODE_TYPE))

#define AFC_TIMING_OPCODE_SET_GET_LINK_STATUS          0
#define AFC_TIMING_NAME_SET_GET_LINK_STATUS          "afc_timing_set_get_link_status"
#define AFC_TIMING_OPCODE_SET_GET_RXEN_STATUS          1
#define AFC_TIMING_NAME_SET_GET_RXEN_STATUS          "afc_timing_set_get_rxen_status"
#define AFC_TIMING_OPCODE_SET_GET_REF_CLK_LOCKED          2
#define AFC_TIMING_NAME_SET_GET_REF_CLK_LOCKED          "afc_timing_set_get_ref_clk_locked"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN0          3
#define AFC_TIMING_NAME_SET_GET_AMC_EN0          "afc_timing_set_get_amc_en0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL0          4
#define AFC_TIMING_NAME_SET_GET_AMC_POL0          "afc_timing_set_get_amc_pol0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG0          5
#define AFC_TIMING_NAME_SET_GET_AMC_LOG0          "afc_timing_set_get_amc_log0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL0          6
#define AFC_TIMING_NAME_SET_GET_AMC_ITL0          "afc_timing_set_get_amc_itl0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC0          7
#define AFC_TIMING_NAME_SET_GET_AMC_SRC0          "afc_timing_set_get_amc_src0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES0          8
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES0          "afc_timing_set_get_amc_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT0          9
#define AFC_TIMING_NAME_SET_GET_AMC_EVT0          "afc_timing_set_get_amc_evt0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY0          10
#define AFC_TIMING_NAME_SET_GET_AMC_DLY0          "afc_timing_set_get_amc_dly0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT0          11
#define AFC_TIMING_NAME_SET_GET_AMC_WDT0          "afc_timing_set_get_amc_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN1          12
#define AFC_TIMING_NAME_SET_GET_AMC_EN1          "afc_timing_set_get_amc_en1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL1          13
#define AFC_TIMING_NAME_SET_GET_AMC_POL1          "afc_timing_set_get_amc_pol1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG1          14
#define AFC_TIMING_NAME_SET_GET_AMC_LOG1          "afc_timing_set_get_amc_log1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL1          15
#define AFC_TIMING_NAME_SET_GET_AMC_ITL1          "afc_timing_set_get_amc_itl1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC1          16
#define AFC_TIMING_NAME_SET_GET_AMC_SRC1          "afc_timing_set_get_amc_src1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES1          17
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES1          "afc_timing_set_get_amc_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT1          18
#define AFC_TIMING_NAME_SET_GET_AMC_EVT1          "afc_timing_set_get_amc_evt1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY1          19
#define AFC_TIMING_NAME_SET_GET_AMC_DLY1          "afc_timing_set_get_amc_dly1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT1          20
#define AFC_TIMING_NAME_SET_GET_AMC_WDT1          "afc_timing_set_get_amc_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN2          21
#define AFC_TIMING_NAME_SET_GET_AMC_EN2          "afc_timing_set_get_amc_en2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL2          22
#define AFC_TIMING_NAME_SET_GET_AMC_POL2          "afc_timing_set_get_amc_pol2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG2          23
#define AFC_TIMING_NAME_SET_GET_AMC_LOG2          "afc_timing_set_get_amc_log2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL2          24
#define AFC_TIMING_NAME_SET_GET_AMC_ITL2          "afc_timing_set_get_amc_itl2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC2          25
#define AFC_TIMING_NAME_SET_GET_AMC_SRC2          "afc_timing_set_get_amc_src2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES2          26
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES2          "afc_timing_set_get_amc_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT2          27
#define AFC_TIMING_NAME_SET_GET_AMC_EVT2          "afc_timing_set_get_amc_evt2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY2          28
#define AFC_TIMING_NAME_SET_GET_AMC_DLY2          "afc_timing_set_get_amc_dly2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT2          29
#define AFC_TIMING_NAME_SET_GET_AMC_WDT2          "afc_timing_set_get_amc_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN3          30
#define AFC_TIMING_NAME_SET_GET_AMC_EN3          "afc_timing_set_get_amc_en3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL3          31
#define AFC_TIMING_NAME_SET_GET_AMC_POL3          "afc_timing_set_get_amc_pol3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG3          32
#define AFC_TIMING_NAME_SET_GET_AMC_LOG3          "afc_timing_set_get_amc_log3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL3          33
#define AFC_TIMING_NAME_SET_GET_AMC_ITL3          "afc_timing_set_get_amc_itl3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC3          34
#define AFC_TIMING_NAME_SET_GET_AMC_SRC3          "afc_timing_set_get_amc_src3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES3          35
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES3          "afc_timing_set_get_amc_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT3          36
#define AFC_TIMING_NAME_SET_GET_AMC_EVT3          "afc_timing_set_get_amc_evt3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY3          37
#define AFC_TIMING_NAME_SET_GET_AMC_DLY3          "afc_timing_set_get_amc_dly3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT3          38
#define AFC_TIMING_NAME_SET_GET_AMC_WDT3          "afc_timing_set_get_amc_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN4          39
#define AFC_TIMING_NAME_SET_GET_AMC_EN4          "afc_timing_set_get_amc_en4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL4          40
#define AFC_TIMING_NAME_SET_GET_AMC_POL4          "afc_timing_set_get_amc_pol4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG4          41
#define AFC_TIMING_NAME_SET_GET_AMC_LOG4          "afc_timing_set_get_amc_log4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL4          42
#define AFC_TIMING_NAME_SET_GET_AMC_ITL4          "afc_timing_set_get_amc_itl4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC4          43
#define AFC_TIMING_NAME_SET_GET_AMC_SRC4          "afc_timing_set_get_amc_src4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES4          44
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES4          "afc_timing_set_get_amc_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT4          45
#define AFC_TIMING_NAME_SET_GET_AMC_EVT4          "afc_timing_set_get_amc_evt4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY4          46
#define AFC_TIMING_NAME_SET_GET_AMC_DLY4          "afc_timing_set_get_amc_dly4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT4          47
#define AFC_TIMING_NAME_SET_GET_AMC_WDT4          "afc_timing_set_get_amc_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN5          48
#define AFC_TIMING_NAME_SET_GET_AMC_EN5          "afc_timing_set_get_amc_en5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL5          49
#define AFC_TIMING_NAME_SET_GET_AMC_POL5          "afc_timing_set_get_amc_pol5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG5          50
#define AFC_TIMING_NAME_SET_GET_AMC_LOG5          "afc_timing_set_get_amc_log5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL5          51
#define AFC_TIMING_NAME_SET_GET_AMC_ITL5          "afc_timing_set_get_amc_itl5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC5          52
#define AFC_TIMING_NAME_SET_GET_AMC_SRC5          "afc_timing_set_get_amc_src5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES5          53
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES5          "afc_timing_set_get_amc_pulses5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT5          54
#define AFC_TIMING_NAME_SET_GET_AMC_EVT5          "afc_timing_set_get_amc_evt5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY5          55
#define AFC_TIMING_NAME_SET_GET_AMC_DLY5          "afc_timing_set_get_amc_dly5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT5          56
#define AFC_TIMING_NAME_SET_GET_AMC_WDT5          "afc_timing_set_get_amc_wdt5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN6          57
#define AFC_TIMING_NAME_SET_GET_AMC_EN6          "afc_timing_set_get_amc_en6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL6          58
#define AFC_TIMING_NAME_SET_GET_AMC_POL6          "afc_timing_set_get_amc_pol6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG6          59
#define AFC_TIMING_NAME_SET_GET_AMC_LOG6          "afc_timing_set_get_amc_log6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL6          60
#define AFC_TIMING_NAME_SET_GET_AMC_ITL6          "afc_timing_set_get_amc_itl6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC6          61
#define AFC_TIMING_NAME_SET_GET_AMC_SRC6          "afc_timing_set_get_amc_src6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES6          62
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES6          "afc_timing_set_get_amc_pulses6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT6          63
#define AFC_TIMING_NAME_SET_GET_AMC_EVT6          "afc_timing_set_get_amc_evt6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY6          64
#define AFC_TIMING_NAME_SET_GET_AMC_DLY6          "afc_timing_set_get_amc_dly6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT6          65
#define AFC_TIMING_NAME_SET_GET_AMC_WDT6          "afc_timing_set_get_amc_wdt6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN7          66
#define AFC_TIMING_NAME_SET_GET_AMC_EN7          "afc_timing_set_get_amc_en7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL7          67
#define AFC_TIMING_NAME_SET_GET_AMC_POL7          "afc_timing_set_get_amc_pol7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG7          68
#define AFC_TIMING_NAME_SET_GET_AMC_LOG7          "afc_timing_set_get_amc_log7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL7          69
#define AFC_TIMING_NAME_SET_GET_AMC_ITL7          "afc_timing_set_get_amc_itl7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC7          70
#define AFC_TIMING_NAME_SET_GET_AMC_SRC7          "afc_timing_set_get_amc_src7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES7          71
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES7          "afc_timing_set_get_amc_pulses7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT7          72
#define AFC_TIMING_NAME_SET_GET_AMC_EVT7          "afc_timing_set_get_amc_evt7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY7          73
#define AFC_TIMING_NAME_SET_GET_AMC_DLY7          "afc_timing_set_get_amc_dly7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT7          74
#define AFC_TIMING_NAME_SET_GET_AMC_WDT7          "afc_timing_set_get_amc_wdt7"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN0          75
#define AFC_TIMING_NAME_SET_GET_FMC1_EN0          "afc_timing_set_get_fmc1_en0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL0          76
#define AFC_TIMING_NAME_SET_GET_FMC1_POL0          "afc_timing_set_get_fmc1_pol0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG0          77
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG0          "afc_timing_set_get_fmc1_log0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL0          78
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL0          "afc_timing_set_get_fmc1_itl0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC0          79
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC0          "afc_timing_set_get_fmc1_src0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES0          80
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES0          "afc_timing_set_get_fmc1_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT0          81
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT0          "afc_timing_set_get_fmc1_evt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY0          82
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY0          "afc_timing_set_get_fmc1_dly0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT0          83
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT0          "afc_timing_set_get_fmc1_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN1          84
#define AFC_TIMING_NAME_SET_GET_FMC1_EN1          "afc_timing_set_get_fmc1_en1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL1          85
#define AFC_TIMING_NAME_SET_GET_FMC1_POL1          "afc_timing_set_get_fmc1_pol1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG1          86
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG1          "afc_timing_set_get_fmc1_log1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL1          87
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL1          "afc_timing_set_get_fmc1_itl1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC1          88
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC1          "afc_timing_set_get_fmc1_src1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES1          89
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES1          "afc_timing_set_get_fmc1_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT1          90
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT1          "afc_timing_set_get_fmc1_evt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY1          91
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY1          "afc_timing_set_get_fmc1_dly1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT1          92
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT1          "afc_timing_set_get_fmc1_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN2          93
#define AFC_TIMING_NAME_SET_GET_FMC1_EN2          "afc_timing_set_get_fmc1_en2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL2          94
#define AFC_TIMING_NAME_SET_GET_FMC1_POL2          "afc_timing_set_get_fmc1_pol2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG2          95
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG2          "afc_timing_set_get_fmc1_log2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL2          96
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL2          "afc_timing_set_get_fmc1_itl2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC2          97
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC2          "afc_timing_set_get_fmc1_src2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES2          98
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES2          "afc_timing_set_get_fmc1_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT2          99
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT2          "afc_timing_set_get_fmc1_evt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY2          100
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY2          "afc_timing_set_get_fmc1_dly2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT2          101
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT2          "afc_timing_set_get_fmc1_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN3          102
#define AFC_TIMING_NAME_SET_GET_FMC1_EN3          "afc_timing_set_get_fmc1_en3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL3          103
#define AFC_TIMING_NAME_SET_GET_FMC1_POL3          "afc_timing_set_get_fmc1_pol3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG3          104
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG3          "afc_timing_set_get_fmc1_log3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL3          105
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL3          "afc_timing_set_get_fmc1_itl3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC3          106
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC3          "afc_timing_set_get_fmc1_src3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES3          107
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES3          "afc_timing_set_get_fmc1_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT3          108
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT3          "afc_timing_set_get_fmc1_evt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY3          109
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY3          "afc_timing_set_get_fmc1_dly3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT3          110
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT3          "afc_timing_set_get_fmc1_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN4          111
#define AFC_TIMING_NAME_SET_GET_FMC1_EN4          "afc_timing_set_get_fmc1_en4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL4          112
#define AFC_TIMING_NAME_SET_GET_FMC1_POL4          "afc_timing_set_get_fmc1_pol4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG4          113
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG4          "afc_timing_set_get_fmc1_log4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL4          114
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL4          "afc_timing_set_get_fmc1_itl4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC4          115
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC4          "afc_timing_set_get_fmc1_src4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES4          116
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES4          "afc_timing_set_get_fmc1_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT4          117
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT4          "afc_timing_set_get_fmc1_evt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY4          118
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY4          "afc_timing_set_get_fmc1_dly4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT4          119
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT4          "afc_timing_set_get_fmc1_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN0          120
#define AFC_TIMING_NAME_SET_GET_FMC2_EN0          "afc_timing_set_get_fmc2_en0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL0          121
#define AFC_TIMING_NAME_SET_GET_FMC2_POL0          "afc_timing_set_get_fmc2_pol0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG0          122
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG0          "afc_timing_set_get_fmc2_log0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL0          123
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL0          "afc_timing_set_get_fmc2_itl0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC0          124
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC0          "afc_timing_set_get_fmc2_src0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES0          125
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES0          "afc_timing_set_get_fmc2_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT0          126
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT0          "afc_timing_set_get_fmc2_evt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY0          127
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY0          "afc_timing_set_get_fmc2_dly0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT0          128
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT0          "afc_timing_set_get_fmc2_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN1          129
#define AFC_TIMING_NAME_SET_GET_FMC2_EN1          "afc_timing_set_get_fmc2_en1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL1          130
#define AFC_TIMING_NAME_SET_GET_FMC2_POL1          "afc_timing_set_get_fmc2_pol1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG1          131
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG1          "afc_timing_set_get_fmc2_log1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL1          132
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL1          "afc_timing_set_get_fmc2_itl1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC1          133
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC1          "afc_timing_set_get_fmc2_src1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES1          134
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES1          "afc_timing_set_get_fmc2_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT1          135
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT1          "afc_timing_set_get_fmc2_evt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY1          136
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY1          "afc_timing_set_get_fmc2_dly1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT1          137
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT1          "afc_timing_set_get_fmc2_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN2          138
#define AFC_TIMING_NAME_SET_GET_FMC2_EN2          "afc_timing_set_get_fmc2_en2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL2          139
#define AFC_TIMING_NAME_SET_GET_FMC2_POL2          "afc_timing_set_get_fmc2_pol2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG2          140
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG2          "afc_timing_set_get_fmc2_log2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL2          141
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL2          "afc_timing_set_get_fmc2_itl2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC2          142
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC2          "afc_timing_set_get_fmc2_src2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES2          143
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES2          "afc_timing_set_get_fmc2_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT2          144
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT2          "afc_timing_set_get_fmc2_evt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY2          145
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY2          "afc_timing_set_get_fmc2_dly2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT2          146
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT2          "afc_timing_set_get_fmc2_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN3          147
#define AFC_TIMING_NAME_SET_GET_FMC2_EN3          "afc_timing_set_get_fmc2_en3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL3          148
#define AFC_TIMING_NAME_SET_GET_FMC2_POL3          "afc_timing_set_get_fmc2_pol3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG3          149
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG3          "afc_timing_set_get_fmc2_log3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL3          150
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL3          "afc_timing_set_get_fmc2_itl3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC3          151
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC3          "afc_timing_set_get_fmc2_src3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES3          152
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES3          "afc_timing_set_get_fmc2_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT3          153
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT3          "afc_timing_set_get_fmc2_evt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY3          154
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY3          "afc_timing_set_get_fmc2_dly3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT3          155
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT3          "afc_timing_set_get_fmc2_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN4          156
#define AFC_TIMING_NAME_SET_GET_FMC2_EN4          "afc_timing_set_get_fmc2_en4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL4          157
#define AFC_TIMING_NAME_SET_GET_FMC2_POL4          "afc_timing_set_get_fmc2_pol4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG4          158
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG4          "afc_timing_set_get_fmc2_log4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL4          159
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL4          "afc_timing_set_get_fmc2_itl4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC4          160
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC4          "afc_timing_set_get_fmc2_src4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES4          161
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES4          "afc_timing_set_get_fmc2_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT4          162
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT4          "afc_timing_set_get_fmc2_evt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY4          163
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY4          "afc_timing_set_get_fmc2_dly4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT4          164
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT4          "afc_timing_set_get_fmc2_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_RTM_FREQ_KP          165
#define AFC_TIMING_NAME_SET_GET_RTM_FREQ_KP          "afc_timing_set_get_rtm_freq_kp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_FREQ_KI          166
#define AFC_TIMING_NAME_SET_GET_RTM_FREQ_KI          "afc_timing_set_get_rtm_freq_ki"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_KP          167
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_KP          "afc_timing_set_get_rtm_phase_kp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_KI          168
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_KI          "afc_timing_set_get_rtm_phase_ki"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_SET          169
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_SET          "afc_timing_set_get_rtm_phase_set"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_NAVG          170
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_NAVG          "afc_timing_set_get_rtm_phase_navg"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_DIV_EXP          171
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_DIV_EXP          "afc_timing_set_get_rtm_phase_div_exp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_RFREQ_HI          172
#define AFC_TIMING_NAME_SET_GET_RTM_RFREQ_HI          "afc_timing_set_get_rtm_rfreq_hi"
#define AFC_TIMING_OPCODE_SET_GET_RTM_RFREQ_LO          173
#define AFC_TIMING_NAME_SET_GET_RTM_RFREQ_LO          "afc_timing_set_get_rtm_rfreq_lo"
#define AFC_TIMING_OPCODE_SET_GET_RTM_N1          174
#define AFC_TIMING_NAME_SET_GET_RTM_N1          "afc_timing_set_get_rtm_n1"
#define AFC_TIMING_OPCODE_SET_GET_RTM_HS_DIV          175
#define AFC_TIMING_NAME_SET_GET_RTM_HS_DIV          "afc_timing_set_get_rtm_hs_div"
#define AFC_TIMING_OPCODE_SET_GET_AFC_FREQ_KP          176
#define AFC_TIMING_NAME_SET_GET_AFC_FREQ_KP          "afc_timing_set_get_afc_freq_kp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_FREQ_KI          177
#define AFC_TIMING_NAME_SET_GET_AFC_FREQ_KI          "afc_timing_set_get_afc_freq_ki"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_KP          178
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_KP          "afc_timing_set_get_afc_phase_kp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_KI          179
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_KI          "afc_timing_set_get_afc_phase_ki"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_SET          180
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_SET          "afc_timing_set_get_afc_phase_set"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_NAVG          181
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_NAVG          "afc_timing_set_get_afc_phase_navg"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_DIV_EXP          182
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_DIV_EXP          "afc_timing_set_get_afc_phase_div_exp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_RFREQ_HI          183
#define AFC_TIMING_NAME_SET_GET_AFC_RFREQ_HI          "afc_timing_set_get_afc_rfreq_hi"
#define AFC_TIMING_OPCODE_SET_GET_AFC_RFREQ_LO          184
#define AFC_TIMING_NAME_SET_GET_AFC_RFREQ_LO          "afc_timing_set_get_afc_rfreq_lo"
#define AFC_TIMING_OPCODE_SET_GET_AFC_N1          185
#define AFC_TIMING_NAME_SET_GET_AFC_N1          "afc_timing_set_get_afc_n1"
#define AFC_TIMING_OPCODE_SET_GET_AFC_HS_DIV          186
#define AFC_TIMING_NAME_SET_GET_AFC_HS_DIV          "afc_timing_set_get_afc_hs_div"

#define AFC_TIMING_OPCODE_END                       187

#endif

