  /*
 * Copyright (C) 2014 LNLS (www.lnls.br)
 * Author: Joao Brito <joao.brito@lnls.br>
 *
 * Released according to the GNU GPL, version 3 or any later version.
 */

#ifndef _SM_IO_AFC_TIMING_CODES_H_
#define _SM_IO_AFC_TIMING_CODES_H_

#include <inttypes.h>

/* Messaging OPCODES */
#define AFC_TIMING_OPCODE_TYPE                    uint32_t
#define AFC_TIMING_OPCODE_SIZE                    (sizeof (AFC_TIMING_OPCODE_TYPE))

#define AFC_TIMING_OPCODE_SET_GET_LINK_STATUS          0
#define AFC_TIMING_NAME_SET_GET_LINK_STATUS          "afc_timing_set_get_link_status"
#define AFC_TIMING_OPCODE_SET_GET_RXEN_STATUS          1
#define AFC_TIMING_NAME_SET_GET_RXEN_STATUS          "afc_timing_set_get_rxen_status"
#define AFC_TIMING_OPCODE_SET_GET_REF_CLK_LOCKED          2
#define AFC_TIMING_NAME_SET_GET_REF_CLK_LOCKED          "afc_timing_set_get_ref_clk_locked"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN0          3
#define AFC_TIMING_NAME_SET_GET_AMC_EN0          "afc_timing_set_get_amc_en0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL0          4
#define AFC_TIMING_NAME_SET_GET_AMC_POL0          "afc_timing_set_get_amc_pol0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG0          5
#define AFC_TIMING_NAME_SET_GET_AMC_LOG0          "afc_timing_set_get_amc_log0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL0          6
#define AFC_TIMING_NAME_SET_GET_AMC_ITL0          "afc_timing_set_get_amc_itl0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC0          7
#define AFC_TIMING_NAME_SET_GET_AMC_SRC0          "afc_timing_set_get_amc_src0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR0          8
#define AFC_TIMING_NAME_SET_GET_AMC_DIR0          "afc_timing_set_get_amc_dir0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES0          9
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES0          "afc_timing_set_get_amc_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT0          10
#define AFC_TIMING_NAME_SET_GET_AMC_EVT0          "afc_timing_set_get_amc_evt0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY0          11
#define AFC_TIMING_NAME_SET_GET_AMC_DLY0          "afc_timing_set_get_amc_dly0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT0          12
#define AFC_TIMING_NAME_SET_GET_AMC_WDT0          "afc_timing_set_get_amc_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN1          13
#define AFC_TIMING_NAME_SET_GET_AMC_EN1          "afc_timing_set_get_amc_en1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL1          14
#define AFC_TIMING_NAME_SET_GET_AMC_POL1          "afc_timing_set_get_amc_pol1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG1          15
#define AFC_TIMING_NAME_SET_GET_AMC_LOG1          "afc_timing_set_get_amc_log1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL1          16
#define AFC_TIMING_NAME_SET_GET_AMC_ITL1          "afc_timing_set_get_amc_itl1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC1          17
#define AFC_TIMING_NAME_SET_GET_AMC_SRC1          "afc_timing_set_get_amc_src1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR1          18
#define AFC_TIMING_NAME_SET_GET_AMC_DIR1          "afc_timing_set_get_amc_dir1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES1          19
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES1          "afc_timing_set_get_amc_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT1          20
#define AFC_TIMING_NAME_SET_GET_AMC_EVT1          "afc_timing_set_get_amc_evt1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY1          21
#define AFC_TIMING_NAME_SET_GET_AMC_DLY1          "afc_timing_set_get_amc_dly1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT1          22
#define AFC_TIMING_NAME_SET_GET_AMC_WDT1          "afc_timing_set_get_amc_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN2          23
#define AFC_TIMING_NAME_SET_GET_AMC_EN2          "afc_timing_set_get_amc_en2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL2          24
#define AFC_TIMING_NAME_SET_GET_AMC_POL2          "afc_timing_set_get_amc_pol2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG2          25
#define AFC_TIMING_NAME_SET_GET_AMC_LOG2          "afc_timing_set_get_amc_log2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL2          26
#define AFC_TIMING_NAME_SET_GET_AMC_ITL2          "afc_timing_set_get_amc_itl2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC2          27
#define AFC_TIMING_NAME_SET_GET_AMC_SRC2          "afc_timing_set_get_amc_src2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR2          28
#define AFC_TIMING_NAME_SET_GET_AMC_DIR2          "afc_timing_set_get_amc_dir2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES2          29
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES2          "afc_timing_set_get_amc_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT2          30
#define AFC_TIMING_NAME_SET_GET_AMC_EVT2          "afc_timing_set_get_amc_evt2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY2          31
#define AFC_TIMING_NAME_SET_GET_AMC_DLY2          "afc_timing_set_get_amc_dly2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT2          32
#define AFC_TIMING_NAME_SET_GET_AMC_WDT2          "afc_timing_set_get_amc_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN3          33
#define AFC_TIMING_NAME_SET_GET_AMC_EN3          "afc_timing_set_get_amc_en3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL3          34
#define AFC_TIMING_NAME_SET_GET_AMC_POL3          "afc_timing_set_get_amc_pol3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG3          35
#define AFC_TIMING_NAME_SET_GET_AMC_LOG3          "afc_timing_set_get_amc_log3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL3          36
#define AFC_TIMING_NAME_SET_GET_AMC_ITL3          "afc_timing_set_get_amc_itl3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC3          37
#define AFC_TIMING_NAME_SET_GET_AMC_SRC3          "afc_timing_set_get_amc_src3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR3          38
#define AFC_TIMING_NAME_SET_GET_AMC_DIR3          "afc_timing_set_get_amc_dir3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES3          39
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES3          "afc_timing_set_get_amc_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT3          40
#define AFC_TIMING_NAME_SET_GET_AMC_EVT3          "afc_timing_set_get_amc_evt3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY3          41
#define AFC_TIMING_NAME_SET_GET_AMC_DLY3          "afc_timing_set_get_amc_dly3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT3          42
#define AFC_TIMING_NAME_SET_GET_AMC_WDT3          "afc_timing_set_get_amc_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN4          43
#define AFC_TIMING_NAME_SET_GET_AMC_EN4          "afc_timing_set_get_amc_en4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL4          44
#define AFC_TIMING_NAME_SET_GET_AMC_POL4          "afc_timing_set_get_amc_pol4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG4          45
#define AFC_TIMING_NAME_SET_GET_AMC_LOG4          "afc_timing_set_get_amc_log4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL4          46
#define AFC_TIMING_NAME_SET_GET_AMC_ITL4          "afc_timing_set_get_amc_itl4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC4          47
#define AFC_TIMING_NAME_SET_GET_AMC_SRC4          "afc_timing_set_get_amc_src4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR4          48
#define AFC_TIMING_NAME_SET_GET_AMC_DIR4          "afc_timing_set_get_amc_dir4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES4          49
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES4          "afc_timing_set_get_amc_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT4          50
#define AFC_TIMING_NAME_SET_GET_AMC_EVT4          "afc_timing_set_get_amc_evt4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY4          51
#define AFC_TIMING_NAME_SET_GET_AMC_DLY4          "afc_timing_set_get_amc_dly4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT4          52
#define AFC_TIMING_NAME_SET_GET_AMC_WDT4          "afc_timing_set_get_amc_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN5          53
#define AFC_TIMING_NAME_SET_GET_AMC_EN5          "afc_timing_set_get_amc_en5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL5          54
#define AFC_TIMING_NAME_SET_GET_AMC_POL5          "afc_timing_set_get_amc_pol5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG5          55
#define AFC_TIMING_NAME_SET_GET_AMC_LOG5          "afc_timing_set_get_amc_log5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL5          56
#define AFC_TIMING_NAME_SET_GET_AMC_ITL5          "afc_timing_set_get_amc_itl5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC5          57
#define AFC_TIMING_NAME_SET_GET_AMC_SRC5          "afc_timing_set_get_amc_src5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR5          58
#define AFC_TIMING_NAME_SET_GET_AMC_DIR5          "afc_timing_set_get_amc_dir5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES5          59
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES5          "afc_timing_set_get_amc_pulses5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT5          60
#define AFC_TIMING_NAME_SET_GET_AMC_EVT5          "afc_timing_set_get_amc_evt5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY5          61
#define AFC_TIMING_NAME_SET_GET_AMC_DLY5          "afc_timing_set_get_amc_dly5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT5          62
#define AFC_TIMING_NAME_SET_GET_AMC_WDT5          "afc_timing_set_get_amc_wdt5"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN6          63
#define AFC_TIMING_NAME_SET_GET_AMC_EN6          "afc_timing_set_get_amc_en6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL6          64
#define AFC_TIMING_NAME_SET_GET_AMC_POL6          "afc_timing_set_get_amc_pol6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG6          65
#define AFC_TIMING_NAME_SET_GET_AMC_LOG6          "afc_timing_set_get_amc_log6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL6          66
#define AFC_TIMING_NAME_SET_GET_AMC_ITL6          "afc_timing_set_get_amc_itl6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC6          67
#define AFC_TIMING_NAME_SET_GET_AMC_SRC6          "afc_timing_set_get_amc_src6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR6          68
#define AFC_TIMING_NAME_SET_GET_AMC_DIR6          "afc_timing_set_get_amc_dir6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES6          69
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES6          "afc_timing_set_get_amc_pulses6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT6          70
#define AFC_TIMING_NAME_SET_GET_AMC_EVT6          "afc_timing_set_get_amc_evt6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY6          71
#define AFC_TIMING_NAME_SET_GET_AMC_DLY6          "afc_timing_set_get_amc_dly6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT6          72
#define AFC_TIMING_NAME_SET_GET_AMC_WDT6          "afc_timing_set_get_amc_wdt6"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EN7          73
#define AFC_TIMING_NAME_SET_GET_AMC_EN7          "afc_timing_set_get_amc_en7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_POL7          74
#define AFC_TIMING_NAME_SET_GET_AMC_POL7          "afc_timing_set_get_amc_pol7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_LOG7          75
#define AFC_TIMING_NAME_SET_GET_AMC_LOG7          "afc_timing_set_get_amc_log7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_ITL7          76
#define AFC_TIMING_NAME_SET_GET_AMC_ITL7          "afc_timing_set_get_amc_itl7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_SRC7          77
#define AFC_TIMING_NAME_SET_GET_AMC_SRC7          "afc_timing_set_get_amc_src7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DIR7          78
#define AFC_TIMING_NAME_SET_GET_AMC_DIR7          "afc_timing_set_get_amc_dir7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_PULSES7          79
#define AFC_TIMING_NAME_SET_GET_AMC_PULSES7          "afc_timing_set_get_amc_pulses7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_EVT7          80
#define AFC_TIMING_NAME_SET_GET_AMC_EVT7          "afc_timing_set_get_amc_evt7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_DLY7          81
#define AFC_TIMING_NAME_SET_GET_AMC_DLY7          "afc_timing_set_get_amc_dly7"
#define AFC_TIMING_OPCODE_SET_GET_AMC_WDT7          82
#define AFC_TIMING_NAME_SET_GET_AMC_WDT7          "afc_timing_set_get_amc_wdt7"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN0          83
#define AFC_TIMING_NAME_SET_GET_FMC1_EN0          "afc_timing_set_get_fmc1_en0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL0          84
#define AFC_TIMING_NAME_SET_GET_FMC1_POL0          "afc_timing_set_get_fmc1_pol0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG0          85
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG0          "afc_timing_set_get_fmc1_log0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL0          86
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL0          "afc_timing_set_get_fmc1_itl0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC0          87
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC0          "afc_timing_set_get_fmc1_src0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES0          88
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES0          "afc_timing_set_get_fmc1_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT0          89
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT0          "afc_timing_set_get_fmc1_evt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY0          90
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY0          "afc_timing_set_get_fmc1_dly0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT0          91
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT0          "afc_timing_set_get_fmc1_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN1          92
#define AFC_TIMING_NAME_SET_GET_FMC1_EN1          "afc_timing_set_get_fmc1_en1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL1          93
#define AFC_TIMING_NAME_SET_GET_FMC1_POL1          "afc_timing_set_get_fmc1_pol1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG1          94
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG1          "afc_timing_set_get_fmc1_log1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL1          95
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL1          "afc_timing_set_get_fmc1_itl1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC1          96
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC1          "afc_timing_set_get_fmc1_src1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES1          97
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES1          "afc_timing_set_get_fmc1_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT1          98
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT1          "afc_timing_set_get_fmc1_evt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY1          99
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY1          "afc_timing_set_get_fmc1_dly1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT1          100
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT1          "afc_timing_set_get_fmc1_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN2          101
#define AFC_TIMING_NAME_SET_GET_FMC1_EN2          "afc_timing_set_get_fmc1_en2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL2          102
#define AFC_TIMING_NAME_SET_GET_FMC1_POL2          "afc_timing_set_get_fmc1_pol2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG2          103
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG2          "afc_timing_set_get_fmc1_log2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL2          104
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL2          "afc_timing_set_get_fmc1_itl2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC2          105
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC2          "afc_timing_set_get_fmc1_src2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES2          106
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES2          "afc_timing_set_get_fmc1_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT2          107
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT2          "afc_timing_set_get_fmc1_evt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY2          108
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY2          "afc_timing_set_get_fmc1_dly2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT2          109
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT2          "afc_timing_set_get_fmc1_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN3          110
#define AFC_TIMING_NAME_SET_GET_FMC1_EN3          "afc_timing_set_get_fmc1_en3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL3          111
#define AFC_TIMING_NAME_SET_GET_FMC1_POL3          "afc_timing_set_get_fmc1_pol3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG3          112
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG3          "afc_timing_set_get_fmc1_log3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL3          113
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL3          "afc_timing_set_get_fmc1_itl3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC3          114
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC3          "afc_timing_set_get_fmc1_src3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES3          115
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES3          "afc_timing_set_get_fmc1_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT3          116
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT3          "afc_timing_set_get_fmc1_evt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY3          117
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY3          "afc_timing_set_get_fmc1_dly3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT3          118
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT3          "afc_timing_set_get_fmc1_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EN4          119
#define AFC_TIMING_NAME_SET_GET_FMC1_EN4          "afc_timing_set_get_fmc1_en4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_POL4          120
#define AFC_TIMING_NAME_SET_GET_FMC1_POL4          "afc_timing_set_get_fmc1_pol4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_LOG4          121
#define AFC_TIMING_NAME_SET_GET_FMC1_LOG4          "afc_timing_set_get_fmc1_log4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_ITL4          122
#define AFC_TIMING_NAME_SET_GET_FMC1_ITL4          "afc_timing_set_get_fmc1_itl4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_SRC4          123
#define AFC_TIMING_NAME_SET_GET_FMC1_SRC4          "afc_timing_set_get_fmc1_src4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_PULSES4          124
#define AFC_TIMING_NAME_SET_GET_FMC1_PULSES4          "afc_timing_set_get_fmc1_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_EVT4          125
#define AFC_TIMING_NAME_SET_GET_FMC1_EVT4          "afc_timing_set_get_fmc1_evt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_DLY4          126
#define AFC_TIMING_NAME_SET_GET_FMC1_DLY4          "afc_timing_set_get_fmc1_dly4"
#define AFC_TIMING_OPCODE_SET_GET_FMC1_WDT4          127
#define AFC_TIMING_NAME_SET_GET_FMC1_WDT4          "afc_timing_set_get_fmc1_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN0          128
#define AFC_TIMING_NAME_SET_GET_FMC2_EN0          "afc_timing_set_get_fmc2_en0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL0          129
#define AFC_TIMING_NAME_SET_GET_FMC2_POL0          "afc_timing_set_get_fmc2_pol0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG0          130
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG0          "afc_timing_set_get_fmc2_log0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL0          131
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL0          "afc_timing_set_get_fmc2_itl0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC0          132
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC0          "afc_timing_set_get_fmc2_src0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES0          133
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES0          "afc_timing_set_get_fmc2_pulses0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT0          134
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT0          "afc_timing_set_get_fmc2_evt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY0          135
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY0          "afc_timing_set_get_fmc2_dly0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT0          136
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT0          "afc_timing_set_get_fmc2_wdt0"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN1          137
#define AFC_TIMING_NAME_SET_GET_FMC2_EN1          "afc_timing_set_get_fmc2_en1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL1          138
#define AFC_TIMING_NAME_SET_GET_FMC2_POL1          "afc_timing_set_get_fmc2_pol1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG1          139
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG1          "afc_timing_set_get_fmc2_log1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL1          140
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL1          "afc_timing_set_get_fmc2_itl1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC1          141
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC1          "afc_timing_set_get_fmc2_src1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES1          142
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES1          "afc_timing_set_get_fmc2_pulses1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT1          143
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT1          "afc_timing_set_get_fmc2_evt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY1          144
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY1          "afc_timing_set_get_fmc2_dly1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT1          145
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT1          "afc_timing_set_get_fmc2_wdt1"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN2          146
#define AFC_TIMING_NAME_SET_GET_FMC2_EN2          "afc_timing_set_get_fmc2_en2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL2          147
#define AFC_TIMING_NAME_SET_GET_FMC2_POL2          "afc_timing_set_get_fmc2_pol2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG2          148
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG2          "afc_timing_set_get_fmc2_log2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL2          149
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL2          "afc_timing_set_get_fmc2_itl2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC2          150
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC2          "afc_timing_set_get_fmc2_src2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES2          151
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES2          "afc_timing_set_get_fmc2_pulses2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT2          152
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT2          "afc_timing_set_get_fmc2_evt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY2          153
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY2          "afc_timing_set_get_fmc2_dly2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT2          154
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT2          "afc_timing_set_get_fmc2_wdt2"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN3          155
#define AFC_TIMING_NAME_SET_GET_FMC2_EN3          "afc_timing_set_get_fmc2_en3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL3          156
#define AFC_TIMING_NAME_SET_GET_FMC2_POL3          "afc_timing_set_get_fmc2_pol3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG3          157
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG3          "afc_timing_set_get_fmc2_log3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL3          158
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL3          "afc_timing_set_get_fmc2_itl3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC3          159
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC3          "afc_timing_set_get_fmc2_src3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES3          160
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES3          "afc_timing_set_get_fmc2_pulses3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT3          161
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT3          "afc_timing_set_get_fmc2_evt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY3          162
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY3          "afc_timing_set_get_fmc2_dly3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT3          163
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT3          "afc_timing_set_get_fmc2_wdt3"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EN4          164
#define AFC_TIMING_NAME_SET_GET_FMC2_EN4          "afc_timing_set_get_fmc2_en4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_POL4          165
#define AFC_TIMING_NAME_SET_GET_FMC2_POL4          "afc_timing_set_get_fmc2_pol4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_LOG4          166
#define AFC_TIMING_NAME_SET_GET_FMC2_LOG4          "afc_timing_set_get_fmc2_log4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_ITL4          167
#define AFC_TIMING_NAME_SET_GET_FMC2_ITL4          "afc_timing_set_get_fmc2_itl4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_SRC4          168
#define AFC_TIMING_NAME_SET_GET_FMC2_SRC4          "afc_timing_set_get_fmc2_src4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_PULSES4          169
#define AFC_TIMING_NAME_SET_GET_FMC2_PULSES4          "afc_timing_set_get_fmc2_pulses4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_EVT4          170
#define AFC_TIMING_NAME_SET_GET_FMC2_EVT4          "afc_timing_set_get_fmc2_evt4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_DLY4          171
#define AFC_TIMING_NAME_SET_GET_FMC2_DLY4          "afc_timing_set_get_fmc2_dly4"
#define AFC_TIMING_OPCODE_SET_GET_FMC2_WDT4          172
#define AFC_TIMING_NAME_SET_GET_FMC2_WDT4          "afc_timing_set_get_fmc2_wdt4"
#define AFC_TIMING_OPCODE_SET_GET_RTM_FREQ_KP          173
#define AFC_TIMING_NAME_SET_GET_RTM_FREQ_KP          "afc_timing_set_get_rtm_freq_kp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_FREQ_KI          174
#define AFC_TIMING_NAME_SET_GET_RTM_FREQ_KI          "afc_timing_set_get_rtm_freq_ki"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_KP          175
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_KP          "afc_timing_set_get_rtm_phase_kp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_KI          176
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_KI          "afc_timing_set_get_rtm_phase_ki"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_SET          177
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_SET          "afc_timing_set_get_rtm_phase_set"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_NAVG          178
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_NAVG          "afc_timing_set_get_rtm_phase_navg"
#define AFC_TIMING_OPCODE_SET_GET_RTM_PHASE_DIV_EXP          179
#define AFC_TIMING_NAME_SET_GET_RTM_PHASE_DIV_EXP          "afc_timing_set_get_rtm_phase_div_exp"
#define AFC_TIMING_OPCODE_SET_GET_RTM_RFREQ_HI          180
#define AFC_TIMING_NAME_SET_GET_RTM_RFREQ_HI          "afc_timing_set_get_rtm_rfreq_hi"
#define AFC_TIMING_OPCODE_SET_GET_RTM_RFREQ_LO          181
#define AFC_TIMING_NAME_SET_GET_RTM_RFREQ_LO          "afc_timing_set_get_rtm_rfreq_lo"
#define AFC_TIMING_OPCODE_SET_GET_RTM_N1          182
#define AFC_TIMING_NAME_SET_GET_RTM_N1          "afc_timing_set_get_rtm_n1"
#define AFC_TIMING_OPCODE_SET_GET_RTM_HS_DIV          183
#define AFC_TIMING_NAME_SET_GET_RTM_HS_DIV          "afc_timing_set_get_rtm_hs_div"
#define AFC_TIMING_OPCODE_SET_GET_AFC_FREQ_KP          184
#define AFC_TIMING_NAME_SET_GET_AFC_FREQ_KP          "afc_timing_set_get_afc_freq_kp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_FREQ_KI          185
#define AFC_TIMING_NAME_SET_GET_AFC_FREQ_KI          "afc_timing_set_get_afc_freq_ki"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_KP          186
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_KP          "afc_timing_set_get_afc_phase_kp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_KI          187
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_KI          "afc_timing_set_get_afc_phase_ki"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_SET          188
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_SET          "afc_timing_set_get_afc_phase_set"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_NAVG          189
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_NAVG          "afc_timing_set_get_afc_phase_navg"
#define AFC_TIMING_OPCODE_SET_GET_AFC_PHASE_DIV_EXP          190
#define AFC_TIMING_NAME_SET_GET_AFC_PHASE_DIV_EXP          "afc_timing_set_get_afc_phase_div_exp"
#define AFC_TIMING_OPCODE_SET_GET_AFC_RFREQ_HI          191
#define AFC_TIMING_NAME_SET_GET_AFC_RFREQ_HI          "afc_timing_set_get_afc_rfreq_hi"
#define AFC_TIMING_OPCODE_SET_GET_AFC_RFREQ_LO          192
#define AFC_TIMING_NAME_SET_GET_AFC_RFREQ_LO          "afc_timing_set_get_afc_rfreq_lo"
#define AFC_TIMING_OPCODE_SET_GET_AFC_N1          193
#define AFC_TIMING_NAME_SET_GET_AFC_N1          "afc_timing_set_get_afc_n1"
#define AFC_TIMING_OPCODE_SET_GET_AFC_HS_DIV          194
#define AFC_TIMING_NAME_SET_GET_AFC_HS_DIV          "afc_timing_set_get_afc_hs_div"
#define AFC_TIMING_OPCODE_SET_GET_EVREN          195
#define AFC_TIMING_NAME_SET_GET_EVREN          "afc_timing_set_get_evren"
#define AFC_TIMING_OPCODE_SET_GET_ALIVE          196
#define AFC_TIMING_NAME_SET_GET_ALIVE          "afc_timing_set_get_alive"

#define AFC_TIMING_OPCODE_END                       197

#endif

