#include "ddr3_map.h"

const acq_buf_t __acq_buf[END_CHAN_ID] = {
  {ADC_CHAN_ID, DDR3_ADC_START_ADDR, DDR3_ADC_END_ADDR, DDR3_ADC_MAX_SAMPLES, DDR3_ADC_SAMPLE_SIZE},
  {TBTAMP_CHAN_ID, DDR3_TBTAMP_START_ADDR, DDR3_TBTAMP_END_ADDR, DDR3_TBTAMP_MAX_SAMPLES, DDR3_TBTAMP_SAMPLE_SIZE},
  {TBTPOS_CHAN_ID, DDR3_TBTPOS_START_ADDR, DDR3_TBTPOS_END_ADDR, DDR3_TBTPOS_MAX_SAMPLES, DDR3_TBTPOS_SAMPLE_SIZE},
  {FOFBAMP_CHAN_ID, DDR3_FOFBAMP_START_ADDR, DDR3_FOFBAMP_END_ADDR, DDR3_FOFBAMP_MAX_SAMPLES, DDR3_FOFBAMP_SAMPLE_SIZE},
  {FOFBPOS_CHAN_ID, DDR3_FOFBPOS_START_ADDR, DDR3_FOFBPOS_END_ADDR, DDR3_FOFBPOS_MAX_SAMPLES, DDR3_FOFBPOS_SAMPLE_SIZE}
};
