#ifndef _DDR3_MAP_AFCV3_H_
#define _DDR3_MAP_AFCV3_H_

#include "acq_chan_afcv3.h"

/* ADC 0 */
#define DDR3_ADC0_SAMPLE_SIZE ADC0_SAMPLE_SIZE
#define DDR3_ADC0_START_ADDR 0x0
#define DDR3_ADC0_END_ADDR (DDR3_ADC0_START_ADDR + 2*MEM_REGION_SIZE - DDR3_ADC0_SAMPLE_SIZE)
#define DDR3_ADC0_MAX_SAMPLES ((DDR3_ADC0_END_ADDR-DDR3_ADC0_START_ADDR) / DDR3_ADC0_SAMPLE_SIZE)

/* TBT 0 AMP */
#define DDR3_TBTAMP0_SAMPLE_SIZE TBTAMP0_SAMPLE_SIZE
#define DDR3_TBTAMP0_START_ADDR (DDR3_ADC0_END_ADDR + DDR3_ADC0_SAMPLE_SIZE)
#define DDR3_TBTAMP0_END_ADDR (DDR3_TBTAMP0_START_ADDR + 2*MEM_REGION_SIZE - DDR3_TBTAMP0_SAMPLE_SIZE)
#define DDR3_TBTAMP0_MAX_SAMPLES ((DDR3_TBTAMP0_END_ADDR-DDR3_TBTAMP0_START_ADDR) / DDR3_TBTAMP0_SAMPLE_SIZE)

/* TBT 0 POS */
#define DDR3_TBTPOS0_SAMPLE_SIZE TBTPOS0_SAMPLE_SIZE
#define DDR3_TBTPOS0_START_ADDR (DDR3_TBTAMP0_END_ADDR + DDR3_TBTAMP0_SAMPLE_SIZE)
#define DDR3_TBTPOS0_END_ADDR (DDR3_TBTPOS0_START_ADDR + MEM_REGION_SIZE - DDR3_TBTPOS0_SAMPLE_SIZE)
#define DDR3_TBTPOS0_MAX_SAMPLES ((DDR3_TBTPOS0_END_ADDR-DDR3_TBTPOS0_START_ADDR) / DDR3_TBTPOS0_SAMPLE_SIZE)

/* FOFB 0 AMP */
#define DDR3_FOFBAMP0_SAMPLE_SIZE FOFBAMP0_SAMPLE_SIZE
#define DDR3_FOFBAMP0_START_ADDR (DDR3_TBTPOS0_END_ADDR + DDR3_TBTPOS0_SAMPLE_SIZE)
#define DDR3_FOFBAMP0_END_ADDR (DDR3_FOFBAMP0_START_ADDR + 2*MEM_REGION_SIZE - DDR3_FOFBAMP0_SAMPLE_SIZE)
#define DDR3_FOFBAMP0_MAX_SAMPLES ((DDR3_FOFBAMP0_END_ADDR-DDR3_FOFBAMP0_START_ADDR) / DDR3_FOFBAMP0_SAMPLE_SIZE)

/* FOFB 0 POS */
#define DDR3_FOFBPOS0_SAMPLE_SIZE FOFBPOS0_SAMPLE_SIZE
#define DDR3_FOFBPOS0_START_ADDR (DDR3_FOFBAMP0_END_ADDR + DDR3_FOFBAMP0_SAMPLE_SIZE)
#define DDR3_FOFBPOS0_END_ADDR (DDR3_FOFBPOS0_START_ADDR + MEM_REGION_SIZE - DDR3_FOFBPOS0_SAMPLE_SIZE)
#define DDR3_FOFBPOS0_MAX_SAMPLES ((DDR3_FOFBPOS0_END_ADDR-DDR3_FOFBPOS0_START_ADDR) / DDR3_FOFBPOS0_SAMPLE_SIZE)

/* ADC 1 */
#define DDR3_ADC1_SAMPLE_SIZE ADC1_SAMPLE_SIZE
#define DDR3_ADC1_START_ADDR (DDR3_FOFBPOS0_END_ADDR + DDR3_FOFBPOS0_SAMPLE_SIZE)
#define DDR3_ADC1_END_ADDR (DDR3_ADC1_START_ADDR + 2*MEM_REGION_SIZE - DDR3_ADC1_SAMPLE_SIZE)
#define DDR3_ADC1_MAX_SAMPLES ((DDR3_ADC1_END_ADDR-DDR3_ADC1_START_ADDR) / DDR3_ADC1_SAMPLE_SIZE)

/* TBT 1 AMP */
#define DDR3_TBTAMP1_SAMPLE_SIZE TBTAMP1_SAMPLE_SIZE
#define DDR3_TBTAMP1_START_ADDR (DDR3_ADC1_END_ADDR + DDR3_ADC1_SAMPLE_SIZE)
#define DDR3_TBTAMP1_END_ADDR (DDR3_TBTAMP1_START_ADDR + 2*MEM_REGION_SIZE - DDR3_TBTAMP1_SAMPLE_SIZE)
#define DDR3_TBTAMP1_MAX_SAMPLES ((DDR3_TBTAMP1_END_ADDR-DDR3_TBTAMP1_START_ADDR) / DDR3_TBTAMP1_SAMPLE_SIZE)

/* TBT 1 POS */
#define DDR3_TBTPOS1_SAMPLE_SIZE TBTPOS1_SAMPLE_SIZE
#define DDR3_TBTPOS1_START_ADDR (DDR3_TBTAMP1_END_ADDR + DDR3_TBTAMP1_SAMPLE_SIZE)
#define DDR3_TBTPOS1_END_ADDR (DDR3_TBTPOS1_START_ADDR + MEM_REGION_SIZE - DDR3_TBTPOS1_SAMPLE_SIZE)
#define DDR3_TBTPOS1_MAX_SAMPLES ((DDR3_TBTPOS1_END_ADDR-DDR3_TBTPOS1_START_ADDR) / DDR3_TBTPOS1_SAMPLE_SIZE)

/* FOFB 1 AMP */
#define DDR3_FOFBAMP1_SAMPLE_SIZE FOFBAMP1_SAMPLE_SIZE
#define DDR3_FOFBAMP1_START_ADDR (DDR3_TBTPOS1_END_ADDR + DDR3_TBTPOS1_SAMPLE_SIZE)
#define DDR3_FOFBAMP1_END_ADDR (DDR3_FOFBAMP1_START_ADDR + 2*MEM_REGION_SIZE - DDR3_FOFBAMP1_SAMPLE_SIZE)
#define DDR3_FOFBAMP1_MAX_SAMPLES ((DDR3_FOFBAMP1_END_ADDR-DDR3_FOFBAMP1_START_ADDR) / DDR3_FOFBAMP1_SAMPLE_SIZE)

/* FOFB 1 POS */
#define DDR3_FOFBPOS1_SAMPLE_SIZE FOFBPOS1_SAMPLE_SIZE
#define DDR3_FOFBPOS1_START_ADDR (DDR3_FOFBAMP1_END_ADDR + DDR3_FOFBAMP1_SAMPLE_SIZE)
#define DDR3_FOFBPOS1_END_ADDR (DDR3_FOFBPOS1_START_ADDR + MEM_REGION_SIZE - DDR3_FOFBPOS1_SAMPLE_SIZE)
#define DDR3_FOFBPOS1_MAX_SAMPLES ((DDR3_FOFBPOS1_END_ADDR-DDR3_FOFBPOS1_START_ADDR) / DDR3_FOFBPOS1_SAMPLE_SIZE)

#endif

